viewRendererConfiguration:
  freemarker:
    strict_syntax: yes
    whitespace_stripping: yes

database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:~/test

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8